<div class="heading">
    <div class="title"><img src="<?=Yii::app()->theme->baseUrl;?>/img/rules_title.png" width="255" height="24" /></div>
    <div class="separator"><img src="<?=Yii::app()->theme->baseUrl;?>/img/hairline.png" width="377" height="2" /></div>
</div>

<div class="text">

<P>GRAMMY Amplifier Contest</p>

<P>Official Rules</p>

<p>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE DOES NOT IMPROVE YOUR CHANCES OF WINNING.</p>

<p><strong>Please read these rules before entering the Contest. By entering and participating in the Contest, you agree to be bound by these Official Rules and represent that you satisfy all of the eligibility requirements set forth below.</strong></p>

<p><strong>1. Overview.&nbsp; </strong>The Recording Academy (&ldquo;Sponsor&rdquo;) is sponsoring the GRAMMY Amplifier, a contest providing undiscovered musicians with an opportunity to enter for a chance to have their music heard and amplified by the music industry and the world.</p>



<p><strong>2. Eligibility.</strong> Participation is open only to legal residents of the fifty United States or the District of Columbia who are at least thirteen (13) years old as of date of entry.&nbsp; Void outside of the 50 United States and the District of Columbia, and where prohibited, taxed or restricted by law.&nbsp; Employees, officers and directors of Sponsor and its parent companies, subsidiaries, affiliates, partners, advertising and promotion agencies, manufacturers or distributors of Contest materials (collectively, the &ldquo;Released Parties&rdquo;) and their immediate families (parents, children, siblings, spouse) or members of the same household (whether related or not) of such employees/officers/directors are not eligible to enter.&nbsp; Contest may only be entered in or from the 50 United States and the District of Columbia, and entries originating from any other jurisdiction are not eligible for entry.&nbsp; You are not authorized to participate in the Contest if you (and all members of your band/group) are not located within the 50 United States or the District of Columbia.&nbsp; All federal, state and local laws and regulations apply.&nbsp; Musicians/bands/groups who, in their current or prior formation, have had any song rank on the Billboard Hot 100 chart or who have received Gold, Platinum or Multi-Platinum certification by the Recording Industry Association of America for a single, shortform album or long-form album are not eligible to enter.</p>



<p><strong>3. </strong><strong>How to Enter.</strong>&nbsp; To enter the GRAMMY Amplifier Contest (&ldquo;Contest&rdquo;), visit <a href="http://www.grammyamplifier.com/">www.GRAMMYAmplifier.com</a> (the &ldquo;Contest Website&rdquo;) between <strong>12:12 AM PST</strong> on <strong>12/12/2012</strong> and <strong>12:12 AM PST</strong> on <strong>2/1/2013 </strong>(the &ldquo;Promotion Period&rdquo;) and follow the directions to post a song from your SoundCloud account (&ldquo;Song&rdquo;) on the Contest Website.&nbsp; In order to post your Song and enter the Contest, you will need to: (i) authorize your SoundCloud account to interoperate with the Contest Website by entering the e-mail address and password linked to your SoundCloud account; (ii) select a Song to submit from your SoundCloud account; (iii) create a profile by using your SoundCloud photo or uploading a photo, tagging your genre and entering your bio; (iv) verify that you (and all members of your band or group, if applicable) are thirteen (13) years of age or older (if any entrant is considered a minor in his/her jurisdiction of residence, the Contest must be entered with permission from his/her parent or legal guardian - which Sponsor reserves the right to verify at any time - and any prize won by a minor will be delivered to the minor&rsquo;s parent/legal guardian and awarded in the name of parent/legal guardian), (v) accept the Official Rules; and (vi) click the &ldquo;Amplify&rdquo; button.&nbsp; All entrants must have a valid email address and SoundCloud account. <strong>Please note:&nbsp; You must have a valid SoundCloud account and agree to the SoundCloud Terms of Use and the SoundCloud Privacy Policy in order to eligible to enter.&nbsp; Registration on SoundCloud must be completed before an entry may be submitted.&nbsp; SoundCloud membership is free.&nbsp; In the event that an entry into the Contest is for or on behalf of a band or other group of musicians, the registered user of the SoundCloud account must have permission from all of the band / group&rsquo;s members, which permission Sponsor reserves the right to verify at any time.&nbsp; Sponsor&rsquo;s computer will be the official time clock for the Contest.&nbsp; Entries</strong><strong> received from any person or email account holder in excess of the stated limitation will be void and Sponsor may disqualify those involved.</strong></p>

<p style="margin-left:.25in;">&nbsp;</p>

<p>Limit one (1) entry per musician/band/group and SoundCloud account.&nbsp; No automated entry devices and/or programs permitted.&nbsp; Entries that contain information that is deemed to be lewd or profane; contain material that violates or infringes on another&rsquo;s rights, including privacy, publicity or intellectual property; material that is hateful or defamatory; material that promotes bigotry, racism, or harm against a group or individual or promotes discrimination; or material that is unlawful or in violation of or contrary to the laws or regulations in any state, will be disqualified as determined solely by Sponsor. All entries will be reviewed for content, and no guarantee is made as to when/if any particular entry will be posted.&nbsp; Entries containing such prohibited content and/or otherwise deemed by Sponsor, in its sole discretion, to be inappropriate will be disqualified.&nbsp; Sponsor makes the final determination as to which Submissions are eligible to take part in the Contest.</p>



<p>All entry information, Songs and submissions shall be collectively referred to herein as the &ldquo;Submissions&rdquo; or each as a &ldquo;Submission.&rdquo; By entering, each entrant warrants and represents the following with respect to their Submission: (a) entrant owns or controls all rights in and to the Submission; (b) the Submission is entrant&rsquo;s own creation; and (c) the Submission will not infringe on any rights of any third parties<strong>.</strong></p>



<p>Receipt of Submissions will not be acknowledged.&nbsp; Sponsor is not responsible for lost, late, illegible, delayed, stolen, incomplete, invalid, unintelligible, misdirected, technically corrupted or garbled entries, which will be disqualified, or for problems of any kind whether mechanical, human or electronic.&nbsp; Proof of submission will not be deemed to be proof of receipt by Sponsor. Entry must be made by the authorized SoundCloud user at the time of entry.</p>

<p><strong>4.</strong> <strong>How to Earn Points.</strong> In order to accumulate points, Entrants must use the &ldquo;share&rdquo; feature on the Contest Website to promote their Submissions.&nbsp; The &ldquo;share&rdquo; feature will enable entrants to generate shareable links to the Contest Website, Facebook and Twitter.&nbsp; Entrants are able to accumulate points by (i) getting Song plays on the Contest Website and (ii) generating social media activity on Twitter and Facebook. Entrants whose Submissions accumulate one thousand (1,000) points during the Promotion Period will be deemed to have reached &ldquo;Curated&rdquo; status (&ldquo;Curated Status&rdquo;).&nbsp;&nbsp;&nbsp;&nbsp;</p>

<p>How to accumulate points on the Contest Website:</p>

<p style="margin-left:.5in;">&bull;&nbsp;&nbsp; Entrant will receive one (1) point each time entrant&rsquo;s Song is played on the Contest Website.&nbsp;</p>

<p>How to accumulate points via Twitter/Facebook:</p>

<p style="margin-left:.5in;">&bull;&nbsp;&nbsp; Entrant will receive a maximum of ten (10) points for one of the following actions (must choose only one): (i) sharing Entrant&rsquo;s own Song on Twitter or (ii) sharing entrant&rsquo;s own Song on entrant&rsquo;s Facebook page.&nbsp; If entrant shares the Song on Twitter, entrant will not be awarded additional points for sharing the Song on entrant&rsquo;s Facebook page.&nbsp; If entrant shares the Song on entrant&rsquo;s Facebook page, entrant will not be awarded additional points for sharing the Song on Twitter.</p>

<p style="margin-left:.5in;">&nbsp;</p>

<p style="margin-left:.5in;">&bull;&nbsp;&nbsp; Entrant will receive a maximum of ten (10) points for one of the following actions performed by a fan who visits the Contest Website (&ldquo;Fan&rdquo;): (i) the sharing of Entrant&rsquo;s Song on Twitter via the Contest Website or (ii) the sharing entrant&rsquo;s Song on the Fan&rsquo;s Facebook page via the Contest Website.&nbsp; If the Fan shares the Song on Twitter, entrant will not be awarded additional points for the Fan&rsquo;s sharing of the Song on the Fan&rsquo;s Facebook page.&nbsp; If the Fan shares the Song on the Fan&rsquo;s Facebook page, entrant will not be awarded additional points for the Fan&rsquo;s sharing the Song on Twitter.</p>

<p><strong>5.</strong> <strong>Judging. </strong>All eligible Submissions that reach Curated Status during the Promotion Period will be judged by a panel of at least five (5) qualified judges selected by Sponsor,. &nbsp;based on the following criteria: Originality, Quality of Composition and Quality of Performance. Sponsor reserves the right to cancel or modify this Contest in the event an insufficient number of Submissions are received that meet the minimum judging criteria. By entering the Contest, entrants fully and unconditionally agree to be bound by these Official Rules and the decisions of the judges, which will be final and binding in all matters relating to the Contest.&nbsp;</p>

<p><strong>6.</strong> <strong>Prize(s).</strong>&nbsp; The judges may select one (1) or more winning Submissions that will receive a Prize. Any Prize winner will have his/her Song Tweeted about by Sponsor or a third party selected by Sponsor. &nbsp;Sponsor shall determine the number and content of any such Tweet in Sponsor&rsquo;s sole discretion.&nbsp; In the event that the quality of the Submissions is insufficient, the judges may, in their discretion, decide not to award any prize.&nbsp; Final designation as a Prize winner depends on verification of eligibility as determined by Sponsor, including but not limited to acceptance of these Official Rules by all members of any band/group entrant.&nbsp; Prize(s) is/are non-transferable.&nbsp; No substitutions or cash redemptions. In the case of unavailability of any prize, Sponsor reserves the right to substitute a prize of equal or greater value in the event the advertised prize becomes unavailable.&nbsp;</p>



<p><strong>7.</strong> <strong>Notification.</strong> Winner(s) will be notified by email and will be required to sign and return, where legal, an Affidavit of Eligibility and Liability/Publicity Release within&nbsp; three (3) days (or such longer time as Sponsor may permit) of prize notification. &nbsp;If any winner is a band/group, all members must sign any required documents.&nbsp; If any winner is considered a minor in his/her jurisdiction of residence, Liability/Publicity Release must be signed by his/her parent or legal guardian and such prize will be delivered to minor&rsquo;s parent/legal guardian and awarded in the name of parent/legal guardian. In the event that the winner is a band or group of musicians, each member must sign and return the Affidavit of Eligibility and Liability/Publicity Release within the required time frame.&nbsp; If any winner cannot be contacted within three (3) calendar days of first notification attempt, if any winner rejects his/her prize or in the event of noncompliance with these Contest rules and requirements, such prize will be forfeited and an alternate winner will be selected from all remaining eligible entries. Upon prize forfeiture, no compensation will be given.&nbsp; Limit one prize per entrant or band/group. Except where prohibited, entry into the Contest and/or acceptance of a prize constitutes consent that the entrant&rsquo;s and winner&rsquo;s (including each member of a band or group if a band or group is a winner) name, photograph, picture, portrait, likeness, voice, biographical data and/or statements made by any entrant and/or winner regarding the Contest or Sponsor may be used for advertising and promotional purposes without limitation and without additional notice, compensation, or consent, except where prohibited by law. By entering, each entrant grants Sponsor the perpetual, unlimited, non-exclusive and irrevocable right to post, publish, adapt, edit, and/or otherwise use the Submission for&nbsp; advertising, marketing, promotional and publicity purposes, including without limitation, in connection with the Contest or the GRAMMY Awards, in any media now known or hereafter developed.</p>



<p><strong>8.</strong> <strong>Conditions.</strong> Any federal, state and local taxes are the sole responsibility of the winner(s).&nbsp; By participating, entrants and winner(s) agree to release and hold harmless the Released Parties, from any and all liability, for loss, harm, damage, injury, cost or expense whatsoever including without limitation, property damage, personal injury and/or death which may occur in connection with, preparation for or participation in Contest, or possession, acceptance and/or use or misuse of prize or participation in any Contest-related activity and for any claims based on publicity rights, defamation or invasion of privacy and merchandise delivery.&nbsp; Sponsor is not responsible if Contest cannot take place or if the prize cannot be awarded due to acts of God, acts of war, natural disasters, weather or acts of terrorism. Entrants who do not comply with these Official Rules, or attempt to interfere with this Contest in any way shall be disqualified. There is no purchase or sales presentation required to participate. A purchase does not increase odds of winning.&nbsp;&nbsp;</p>



<p><strong>9.</strong> <strong>Additional Terms.</strong> In case of dispute as to the identity of any entrant, entry will be declared made by the authorized account holder of the email address submitted at time of entry. &ldquo;Authorized Account Holder&rdquo; is defined as the natural person who is assigned an email address by an Internet access provider, online service provider, or other organization (e.g., business, educational, institution, etc.) responsible for assigning email addresses or the domain associated with the submitted email address. Any potential winner may be requested to provide Sponsor with proof that such winner is the authorized account holder of the email address associated with the winning entry.&nbsp; Any other attempted form of entry is prohibited; no automatic, programmed; robotic or similar means of entry are permitted. The Released Parties are not responsible for technical, hardware, software, telephone or other communications malfunctions, errors or failures of any kind, lost or unavailable network connections, web site, Internet, or ISP availability, unauthorized human intervention, traffic congestion, incomplete or inaccurate capture of entry information (regardless of cause) or failed, incomplete, garbled, jumbled or delayed computer transmissions which may limit one&rsquo;s ability to enter the Contest, including any injury or damage to participant&rsquo;s or any other person&rsquo;s computer relating to or resulting from participating in this Contest or downloading any materials in this Contest.&nbsp; Sponsor reserves the right, in its sole discretion, to cancel, terminate, modify, extend or suspend this Contest should (in its sole discretion) virus, bugs, non-authorized human intervention, fraud or other causes beyond its control corrupt or affect the administration, security, fairness or proper conduct of the Contest. In such case, Sponsor may select the winner(s) in a fair and equitable manner, as determined by Sponsor in its discretion, in light of the circumstances.&nbsp; Sponsor reserves the right, at its sole discretion, to disqualify any individual it finds, in its sole discretion, to be tampering with the entry or points-accumulation process or the operation of the Contest or web site.&nbsp; Sponsor may prohibit an entrant from participating in the Contest or winning a prize if, in its sole discretion, it determines that said entrant is attempting to undermine the legitimate operation of the Contest by cheating, hacking, deception, or other unfair playing practices (including the use of automated quick entry programs) or intending to annoy, abuse, threaten or harass any other entrants or Sponsor representatives.</p>

<p>CAUTION: ANY ATTEMPT BY AN ENTRANT TO DELIBERATELY DAMAGE ANY WEB SITE OR UNDERMINE THE LEGITIMATE OPERATION OF THE CONTEST MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAWS AND SHOULD SUCH AN ATTEMPT BE MADE, THE SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES FROM ANY SUCH PERSON TO THE FULLEST EXTENT PERMITTED BY LAW.</p>

<p><strong>10.</strong><strong>&nbsp; Limitation of Liability; Disclaimer of Warranties. </strong>The Released Parties are not responsible for: (a) any incorrect or inaccurate information, whether caused by entrant, printing errors or by any of the equipment or programming associated with or utilized in the Contest; (b) technical failures of any kind, including, but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software; (c) unauthorized human intervention in any part of the entry process or the Contest; (d) printing, typographical, technical, computer, network or human error which may occur in the administration of the Contest, the uploading, the processing or judging of Submissions or points or the tabulating of points, the announcement of the prizes or in any Contest-related materials; or (e) any injury or damage to persons or property which may be caused, directly or indirectly, in whole or in part, from entrant&rsquo;s participation in the Contest or receipt or use or misuse of any prize.&nbsp; Released Parties are not responsible for any unauthorized third party use of any Submission.&nbsp; If for any reason an entrant&#39;s Submission is confirmed to have been erroneously deleted, lost, or otherwise destroyed or corrupted, entrant&rsquo;s sole remedy is the ability to upload another Submission into the Contest, provided that if it is not possible due to discontinuance of the Contest, or any part of it, for any reason, Sponsor, in its sole discretion, may determine the potential winners from all of the eligible Submissions received up to the date of discontinuance for any or all of the prizes offered herein. No more than the stated number of prizes will be awarded. IN NO EVENT WILL THE RELEASED PARTIES BE RESPONSIBLE OR LIABLE FOR ANY DAMAGES OR LOSSES OF ANY KIND, INCLUDING DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF YOUR ACCESS TO AND USE OF THE SERVICE AND/OR THE CONTEST, DOWNLOADING FROM AND/OR PRINTING MATERIAL DOWNLOADED FROM ANY WEBSITES ASSOCIATES WITH THE CONTEST. WITHOUT LIMITING THE FOREGOING, THIS CONTEST AND ALL PRIZES ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. SOME JURISDICTIONS MAY NOT ALLOW THE LIMITATIONS OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES OR EXCLUSION OF IMPLIED WARRANTIES SO SOME OF THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. CHECK YOUR LOCAL LAWS FOR ANY RESTRICTIONS OR LIMITATIONS REGARDING THESE LIMITATIONS OR EXCLUSIONS.</p>

<p><strong>11. Disputes; Governing Law.&nbsp; </strong>The parties waive all rights to trial in any action or proceeding instituted in connection with these Official Rules, including, without limitation, the Contest. Any controversy or claim arising out of or relating to these Official Rules and/or the Contest shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration shall be conducted in the State of California, City of Los Angeles.</p>

<p>THESE OFFICIAL RULES AND THE INTERPRETATION OF ITS TERMS SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF CALIFORNIA WITHOUT REGARD TO ITS CONFLICTS OF LAWS RULES. For any matters which are not subject to arbitration as set forth in these Official Rules and/or in connection with the entering of any judgment on an arbitration award in connection with these Official Rules and/or the Contest, the parties irrevocably submit and consent to the exclusive jurisdiction and venue of the state and federal courts located in or closest to the County of Los Angeles in the State of California. The parties agree not to raise the defense of forum non conveniens.</p>

<p><strong>12. Use of Data.</strong>&nbsp; Sponsor will be collecting personal data about entrants online, in accordance with its privacy policy.&nbsp; Please review the Sponsor&rsquo;s privacy policy at <strong>http://www.grammy.com/legal#privacy.&nbsp; </strong>By participating in the Contest, entrants hereby agree to Sponsor&rsquo;s collection and usage of their personal information and acknowledge that they have read and accepted Sponsor&rsquo;s privacy policy.&nbsp;</p>

<p><strong>13.</strong> <strong>List of Winners/Winner&rsquo;s Name.</strong> To obtain a list of winners/the name of the winner, send a self-addressed, stamped envelope by <strong>3/1/2013</strong> to: <strong>ATTN:</strong> <strong>Grammy Amplifier Winners</strong>, <strong>The Recording Academy</strong> <strong>3030 Olympic Blvd, Santa Monica, CA 90404</strong>.</p>

<p><strong>13.</strong> <strong>Sponsor.</strong> The Recording Academy, 3030 Olympic Boulevard, Santa Monica, CA 90404.</p>

















</div>